version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: usuario1
      POSTGRES_PASSWORD: pasword1234
      # Esta será la DB "por defecto"
      POSTGRES_DB: usuario1 
    ports:
      - "5433:5432"
    # Este comando crea la base de datos adicional si no existe
    command: >
      sh -c "docker-entrypoint.sh postgres &
      sleep 5;
      psql -U usuario1 -d usuario1 -c 'CREATE DATABASE order_db;' || true;
      wait"
    restart: always

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario1
      MONGO_INITDB_ROOT_PASSWORD: pasword1234
    ports:
      - "27017:27017"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always